### ISSUE TITLE
Can you create another extension that disables all single key shortcuts?

### ISSUE THREAD

**Issue by rubo77** [heisencoder/keyfixer#1]
I think you have the knowledge to solve this issue to creat an extension for Thunderbird that disables single-key shordtkuts like J for Junk and A vor archive...

That would be so cool, maybe you can help here?

http://superuser.com/questions/334191/how-can-i-customize-keyboard-shortcuts-in-thunderbird

**Comment by heisencoder** [comment]
Hi Ruben,

At this point I've mostly (if not entirely) dropped support for the
keyfixer extension for Firefox and Thunderbird.  I haven't used either
product for over 4 years now.  Now, I use Chrome and Gmail.  As such, I
unfortunately don't have the time or motivation to support the Mozilla-like
platforms anymore.

Cheers,
-Matt

On Wed, Oct 8, 2014 at 3:48 PM, Ruben Barkow notifications@github.com
wrote:

> I think you have the knowledge to solve this issue to creat an extension
> for Thunderbird that disables single-key shordtkuts like J for Junk and A
> vor archive...
> 
> That would be so cool, maybe you can help here?
> 
> http://superuser.com/questions/334191/how-can-i-customize-keyboard-shortcuts-in-thunderbird
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/heisencoder/keyfixer/issues/1.

## 

Thanks!

Matt Ball
Cell: 303-717-2717
